---
system: 
  time: 0.2
  behavior: tor
  size_x: 5
  size_y: 5

#integral: 
#  step: 0.001

#dump:
#  step:
#  detector:

#mol: 
#  step: 0.005
#  detector: surf

#sdf:
#  step:
#  detector:

xyz:
  step: 0.001
  detector: surf

progress:
  step: 0.001
